### ISSUE TITLE
Using of Dust / PAH with personal snapshots

### ISSUE THREAD

**Issue by ACDylan** [dnarayanan/powderday#138]
Hi,

I wanted to use my own snapshots, adding PAH = True, but I have the following issue:
```
Traceback (most recent call last):
  File "/home/chosson/local/Python-3.9.4/bin/pd_front_end.py", line 4, in <module>
    __import__('pkg_resources').run_script('powderday==0.1.0', 'pd_front_end.py')
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/powderday-0.1.0-py3.9.egg/EGG-INFO/scripts/pd_front_end.py", line 74, in <module>
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/powderday-0.1.0-py3.9.egg/powderday/sph_tributary.py", line 138, in sph_m_gen
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/hyperion/dust/dust_type.py", line 76, in __init__
    self.read(args[0])
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/hyperion/dust/dust_type.py", line 315, in read
    dt = h5py.File(filename, 'r')
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```

Looking on Google, it seems to be a "corrupted data" issue with the hdf5's dust.
However, with python in command line, both give me:
```
>>> import h5py
>>> f = h5py.File('d03_5.5_3.0_A.hdf5','r')
>>> list(f.keys())
['emissivities', 'emissivity_variable', 'mean_opacities', 'optical_properties', 'scattering_angles']
```
```
>>> f = h5py.File('snapshot_240.hdf5','r')
>>> list(f.keys())
['Header', 'PartType0', 'PartType1', 'PartType2', 'PartType3', 'PartType4', 'Units']
```

So, I am asking myself if this is due to an external error, or directly related with a pd sub-code.

**Comment by dnarayanan** [comment]
Hi,

does this work for you with the example problems (like gizmo_mw)?  I've been using with PAH=True quite regularly recently.

**Comment by ACDylan** [comment]
Hi,

Just try again and sadly no, it didn't work with gizmo_mw when I set PAH=True

**Comment by ACDylan** [comment]
Hi,

I am trying to run (and possibly debug) my PAH issue.
The last one about H5 file (from a month ago) seems to be resolved. However, now it is telling that
`Exception: File not found: /home/chosson/POWDERDAY/hyperion-dust-0.1.0/dust_files/usg.hdf5`

and I cannot find on internet what kind of file it is supposed to be.

The complete issue being:

```
Setting Octree Grid with Parameters:
INFO: Checking consistency of refined array [hyperion.grid.octree_grid]
INFO: Setting refined with maximum depth of 13 levels [hyperion.grid.octree_grid]
Traceback (most recent call last):
  File "/home/chosson/local/Python-3.9.4/bin/pd_front_end.py", line 4, in <module>
    __import__('pkg_resources').run_script('powderday==0.1.0', 'pd_front_end.py')
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/powderday-0.1.0-py3.9.egg/EGG-INFO/scripts/pd_front_end.py", line 74, in <module>
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/powderday-0.1.0-py3.9.egg/powderday/sph_tributary.py", line 138, in sph_m_gen
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/hyperion/dust/dust_type.py", line 76, in __init__
    self.read(args[0])
  File "/home/chosson/local/Python-3.9.4/lib/python3.9/site-packages/hyperion/dust/dust_type.py", line 312, in read
    raise Exception("File not found: %s" % filename)
Exception: File not found: /home/chosson/POWDERDAY/hyperion-dust-0.1.0/dust_files/usg.hdf5
```

I reinstalled hyperion-dust-0.1.0 to see if this 'usg.hdf5' appears but it is still missing.
How / where am I supposed to get this file?

**Comment by dnarayanan** [comment]
Hi - yep these files require a separate download. Please see:

https://powderday.readthedocs.io/en/latest/installation.html#hyperion-dust-files

**Comment by ACDylan** [comment]
It works now! So I hope this will work for my other snapshots as well.
