### ISSUE TITLE
yt 3.0 backwards compatibility 

### ISSUE THREAD

**Issue by prerakgarg07** [dnarayanan/powderday#147]
After the change in nomenclature introduced in commit   #133 The code is no longer backwards compatible with yt 3 (I have tried it with yt 3.6.1)

```
yt : [WARNING  ] 2021-09-29 09:11:58,893 Field ('gas', 'density') already exists. To override use force_override=True.
----------------------------
[octree zoom_bbox_filter:] Calculating Center of Mass
Traceback (most recent call last):
  File "pd_front_end.py", line 74, in <module>
    m, xcent, ycent, zcent, dx, dy, dz, reg, ds, boost = m_gen(fname, field_add)
  File "/blue/narayanan/prerakgarg/powderday/powderday/sph_tributary.py", line 35, in sph_m_gen
    refined,dustdens,fc1,fw1,reg,ds = yt_octree_generate(fname,field_add)
  File "/blue/narayanan/prerakgarg/powderday/powderday/grid_construction.py", line 54, in yt_octree_generate
    reg = octree_zoom_bbox_filter(fname, ds, bbox, field_add)
  File "/blue/narayanan/prerakgarg/powderday/powderday/zoom.py", line 25, in octree_zoom_bbox_filter
    gas_com_x = np.sum(ad["gas","density"] * ad["gas","coordinates"][:,0])/np.sum(ad["gas","density"])
  File "/blue/narayanan/prerakgarg/codes/anaconda3/envs/pd_test_env/lib/python3.7/site-packages/yt/data_objects/data_containers.py", line 249, in __getitem__
    f = self._determine_fields([key])[0]
  File "/blue/narayanan/prerakgarg/codes/anaconda3/envs/pd_test_env/lib/python3.7/site-packages/yt/data_objects/data_containers.py", line 1387, in _determine_fields
    raise YTFieldTypeNotFound(ftype, ds=self.ds)
yt.utilities.exceptions.YTFieldTypeNotFound: Could not find field type 'gas'.```

**Comment by dnarayanan** [comment]
I wonder if it's worth completely leaving yt3.x behind and making pd no longer support 3.x....
